### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by BugBuster27** [billonium4535/BetterDiscord#24]
Create an installer as a stand alone `.exe` that will:
 - Download the `.zip` file of the latest client build.
 - Ask the user where they want to install the program to.
 - Extract the files.

**Comment by BugBuster27** [comment]
## To Close Issue
1. Port 8459 needs opening on the router.
2. Create folder `Latest_Version` under `./server` on the server.
3. Host `BetterDiscord.zip` in the folder.

**Comment by billonium4535** [comment]
Fixed https://github.com/billonium4535/BetterDiscord/issues/24#issuecomment-1927412322
