### ISSUE TITLE
Server Connection Issue

### ISSUE THREAD

**Issue by billonium4535** [billonium4535/BetterDiscord#6]
If the client opens and can't connect to the server, it crashes.
Add error handling/loading screen for this and if the client loses connection.

Modify messages so that when the user sends a message to the server, the server responds to acknowledge it received it.

**Comment by BugBuster27** [comment]
Create a loading screen where the user can't do anything on the UI until a connection with the server is made (add to #20).
When the connection is made, go into the main running loop.
If the connection breaks, go back to the loading screen.

**Comment by BugBuster27** [comment]
[> Create a loading screen where the user can't do anything on the UI until a connection with the server is made (add to #20). When the connection is made, go into the main running loop. If the connection breaks, go back to the loading screen.](https://github.com/billonium4535/BetterDiscord/issues/6#issuecomment-1908310092)

Loading screen is created, need to keep checking if it is connected to the server and if not, go back to the loading screen.
The server no longer crashes when a client disconnects.
